import Foundation

@main struct LearningTests {
    @MainActor static func main() throws {
        let widgetSuite = "widget-tests-" + UUID().uuidString
        let widgetDefaults = UserDefaults(suiteName: widgetSuite)!
        defer { widgetDefaults.removePersistentDomain(forName: widgetSuite) }
        precondition(WidgetProgress.read(from: widgetDefaults) == nil)
        precondition(WidgetProgress.example.total == 8000)
        precondition(WidgetProgress.example.write(to: widgetDefaults))
        precondition(WidgetProgress.read(from: widgetDefaults) == .example)
        precondition(!WidgetProgress.example.write(to: widgetDefaults))
        precondition(WidgetProgress.empty.write(to: widgetDefaults))
        precondition(WidgetProgress.read(from: widgetDefaults)?.total == 0)
        widgetDefaults.set(Data("invalid".utf8), forKey: WidgetProgress.key)
        precondition(WidgetProgress.read(from: widgetDefaults) == nil)
        let simple = "カテゴリー,問題,答え,意味\n読み,桜,さくら,春の木\n読み,椿,つばき,"
        let parsed = try KanjiCSV.parse(simple)
        precondition(parsed.count == 2 && parsed.allSatisfy { $0.mastery == .starting })
        let complex = try KanjiCSV.parse("\u{FEFF}答え,意味,カテゴリー,問題\r\nさくら,\"春,花\n\"\"桜\"\"\",読み,桜\r\n")
        precondition(complex[0].meaning == "春,花\n\"桜\"")
        precondition(complex[0].question == "桜")
        for invalid in ["", "カテゴリー,問題,答え,意味", "問題,答え\n桜,さくら", "カテゴリー,問題,答え,意味\n読み,,さくら,木", "カテゴリー,問題,答え,意味\n読み,桜,さくら,\"未終了", "カテゴリー,問題,答え,意味\n読み,桜,さくら,\"木\"x"] {
            do { _ = try KanjiCSV.parse(invalid); preconditionFailure("Invalid CSV accepted") }
            catch is LearningError { }
        }
        let sjis = simple.data(using: .shiftJIS)!
        let decoded = try KanjiCSV.decode(sjis)
        precondition(decoded.count == 2)
        let directory = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        defer { try? FileManager.default.removeItem(at: directory) }
        let url = directory.appendingPathComponent("items.json")
        let store = LearningStore(fileURL: url)
        precondition(store.items.isEmpty)
        precondition(store.add(parsed))
        precondition(store.setMastery(.mastered, for: parsed[0].id))
        let reloaded = LearningStore(fileURL: url)
        precondition(reloaded.items.count == 2)
        precondition(reloaded.item(parsed[0].id)?.mastery == .mastered)
        precondition(reloaded.filtered(category: "読み", mastery: .mastered).count == 1)
        precondition(reloaded.filtered(category: "ことわざ", mastery: nil).isEmpty)
        precondition(reloaded.filtered(category: nil, mastery: nil, search: " 桜\n").map(\.id) == [parsed[0].id])
        precondition(reloaded.filtered(category: nil, mastery: nil, search: "  ").count == 2)
        precondition(reloaded.filtered(category: "読み", mastery: .mastered, search: "桜").count == 1)
        precondition(reloaded.filtered(category: "読み", mastery: .starting, search: "桜").isEmpty)
        precondition(reloaded.filtered(category: "ことわざ", mastery: nil, search: "桜").isEmpty)
        precondition(reloaded.filtered(category: nil, mastery: nil, search: " くら\n").map(\.id) == [parsed[0].id])
        precondition(reloaded.filtered(category: "読み", mastery: .mastered, search: "さくら").map(\.id) == [parsed[0].id])
        precondition(reloaded.filtered(category: "読み", mastery: .starting, search: "さくら").isEmpty)
        precondition(reloaded.filtered(category: "ことわざ", mastery: nil, search: "さくら").isEmpty)
        for query in ["春の木", "読み", "存在しない"] {
            precondition(reloaded.filtered(category: nil, mastery: nil, search: query).isEmpty)
        }
        let searchURL = directory.appendingPathComponent("search.json")
        let searchStore = LearningStore(fileURL: searchURL)
        var searchItem = StudyItem(category: "音読み", question: "炊爨", answer: "すいさん", meaning: "飯を炊く")
        searchItem.notes = "検索対象外のメモ"
        precondition(searchStore.add([searchItem]))
        precondition(searchStore.filtered(category: nil, mastery: nil, search: "爨").count == 1)
        precondition(searchStore.filtered(category: nil, mastery: nil, search: "すいさん").map(\.id) == [searchItem.id])
        let fillInItem = StudyItem(category: "四字熟語", question: "拳拳____", answer: "服膺", meaning: "心に銘記する")
        let overlappingItem = StudyItem(category: "読み", question: "さくら（桜）", answer: "さくら", meaning: "")
        precondition(searchStore.add([fillInItem, overlappingItem]))
        precondition(searchStore.filtered(category: nil, mastery: nil, search: "服膺").map(\.id) == [fillInItem.id])
        precondition(searchStore.filtered(category: nil, mastery: nil, search: "さくら").map(\.id) == [overlappingItem.id])
        precondition(searchStore.filtered(category: nil, mastery: nil, search: "検索対象外").isEmpty)
        for query in ["", "  ", "炊", "すいさん", " 服膺\n", "さくら", "検索対象外"] {
            for selectedCategory in [nil, "音読み", "四字熟語"] as [String?] {
                for selectedMastery in [nil, .starting, .mastered] as [Mastery?] {
                    let result = searchStore.searchResults(category: selectedCategory, mastery: selectedMastery, search: query)
                    precondition(result.items == searchStore.filtered(category: selectedCategory, mastery: selectedMastery, search: query))
                    precondition(result.total == searchStore.filtered(category: selectedCategory, mastery: nil, search: query).count)
                    for value in Mastery.allCases {
                        precondition(result.counts[value, default: 0] == searchStore.filtered(category: selectedCategory, mastery: value, search: query).count)
                    }
                }
            }
        }
        precondition(searchStore.searchResults(category: nil, mastery: nil, search: "すいさん").answerOnlyIDs == [searchItem.id])
        precondition(searchStore.searchResults(category: nil, mastery: nil, search: "さくら").answerOnlyIDs.isEmpty)
        precondition(searchStore.searchResults(category: nil, mastery: nil, search: " ").answerOnlyIDs.isEmpty)
        var session = StudySession(items: parsed)
        let firstCompanion = session.companionName
        precondition(StudySession.companionNames.contains(firstCompanion))
        let originalSession = session
        precondition(Set(session.itemIDs) == Set(parsed.map(\.id)))
        precondition(!session.revealed && !session.isReview)
        precondition(!session.canGoBack)
        session.goBack()
        precondition(session == originalSession)
        session.revealed = true; session.advance()
        precondition(session != originalSession)
        precondition(session.index == 1 && !session.revealed)
        precondition(session.companionName != firstCompanion)
        let secondCompanion = session.companionName
        let secondID = session.currentID
        precondition(session.canGoBack)
        session.revealed = true
        session.goBack()
        precondition(session.companionName == firstCompanion)
        precondition(session.currentID == originalSession.currentID && !session.revealed)
        precondition(session.itemIDs == originalSession.itemIDs && !session.canGoBack)
        session.advance()
        precondition(session.currentID == secondID)
        precondition(session.companionName == secondCompanion)
        session.advance(); precondition(session.complete)
        let completedSession = session
        session.goBack()
        precondition(session == completedSession)
        var review = StudySession(items: [parsed[0]], review: true)
        review.goBack()
        precondition(review.revealed && review.isReview)
        // Migration from records without a notes key.
        let encoded = try JSONEncoder().encode(parsed)
        var legacy = try JSONSerialization.jsonObject(with: encoded) as! [[String: Any]]
        for index in legacy.indices { legacy[index].removeValue(forKey: "notes") }
        let migrated = try JSONDecoder().decode([StudyItem].self, from: JSONSerialization.data(withJSONObject: legacy))
        precondition(migrated.allSatisfy { $0.notes.isEmpty })
        var edited = reloaded.items[0]
        edited.category = "訓読み"; edited.question = "梅"; edited.answer = "うめ"
        edited.meaning = "春の花"; edited.notes = "覚え方\n補足"
        precondition(reloaded.update(edited))
        let editedStore = LearningStore(fileURL: url)
        precondition(editedStore.item(edited.id) == edited)
        precondition(editedStore.delete(edited.id))
        precondition(LearningStore(fileURL: url).item(edited.id) == nil)
        precondition(!editedStore.update(edited))
        let invalidURL = directory.appendingPathComponent("not-a-directory")
        try Data("block".utf8).write(to: invalidURL)
        let failedStore = LearningStore(fileURL: invalidURL.appendingPathComponent("items.json"))
        precondition(!failedStore.add(parsed) && failedStore.items.isEmpty)
        let failureURL = directory.appendingPathComponent("failure.json")
        let writeFailureStore = LearningStore(fileURL: failureURL)
        precondition(writeFailureStore.add([edited]))
        try FileManager.default.removeItem(at: failureURL)
        try FileManager.default.createDirectory(at: failureURL, withIntermediateDirectories: false)
        var unsaved = edited
        unsaved.notes = "保存されない変更"
        precondition(!writeFailureStore.update(unsaved))
        precondition(writeFailureStore.item(edited.id) == edited)
        precondition(!writeFailureStore.delete(edited.id))
        precondition(writeFailureStore.item(edited.id) == edited)
        try Data("corrupt".utf8).write(to: url)
        let corrupt = LearningStore(fileURL: url)
        precondition(corrupt.errorMessage != nil && !corrupt.add(parsed))
        let preserved = try String(contentsOf: url, encoding: .utf8)
        precondition(preserved == "corrupt")
        let defaultsURL = URL(fileURLWithPath: "KanjiBuildUp/Resources/DefaultStudyData.json")
        let defaults = try JSONDecoder().decode(DefaultStudyData.self, from: Data(contentsOf: defaultsURL))
        precondition(defaults.items.count == 2974)
        precondition(defaults.items.filter { $0.mastery == .starting }.count == 2308)
        precondition(defaults.items.filter { $0.mastery == .learning }.count == 130)
        precondition(defaults.items.filter { $0.mastery == .mastered }.count == 536)
        let seededURL = directory.appendingPathComponent("seeded.json")
        let seeded = LearningStore(fileURL: seededURL, defaults: defaults)
        precondition(seeded.items == defaults.items)
        let first = defaults.items[0]
        precondition(first.notes == "逞筆さん411番")
        precondition(seeded.setMastery(.mastered, for: first.id))
        precondition(seeded.delete(defaults.items[1].id))
        let restarted = LearningStore(fileURL: seededURL, defaults: defaults)
        precondition(restarted.items.count == 2973)
        precondition(restarted.item(first.id)?.mastery == .mastered)
        precondition(restarted.item(defaults.items[1].id) == nil)
        let yojiURL = URL(fileURLWithPath: "KanjiBuildUp/Resources/YojiKakiStudyData.json")
        let yoji = try JSONDecoder().decode(DefaultStudyData.self, from: Data(contentsOf: yojiURL))
        precondition(yoji.items.count == 1605)
        precondition(yoji.items.filter { $0.mastery == .starting }.count == 198)
        precondition(yoji.items.filter { $0.mastery == .learning }.count == 388)
        precondition(yoji.items.filter { $0.mastery == .mastered }.count == 1019)
        precondition(yoji.items[1057].mastery == .starting)
        precondition(yoji.items[1058].mastery == .mastered)
        precondition(yoji.items[1059].mastery == .learning)
        precondition(yoji.items[1604].mastery == .starting)
        precondition(yoji.items[4].answer == "縹渺\n縹緲\n 縹眇")
        precondition(yoji.items[0].notes == "逞筆さん1番\n出典：＊『礼記-中庸』")
        var personal = restarted.item(first.id)!
        personal.notes = "編集したメモ"
        precondition(restarted.update(personal))
        let expanded = LearningStore(fileURL: seededURL, defaults: defaults, additionalDefaults: [yoji])
        precondition(expanded.items.count == 4578)
        precondition(expanded.item(first.id) == personal)
        precondition(expanded.item(defaults.items[1].id) == nil)
        precondition(expanded.item(yoji.items[0].id) == yoji.items[0])
        precondition(expanded.delete(yoji.items[0].id))
        precondition(expanded.setMastery(.mastered, for: yoji.items[1059].id))
        let expandedRestart = LearningStore(fileURL: seededURL, defaults: defaults, additionalDefaults: [yoji])
        precondition(expandedRestart.items.count == 4577)
        precondition(expandedRestart.item(yoji.items[0].id) == nil)
        precondition(expandedRestart.item(yoji.items[1059].id)?.mastery == .mastered)
        let kojikotoURL = URL(fileURLWithPath: "KanjiBuildUp/Resources/KojikotoStudyData.json")
        let kojikoto = try JSONDecoder().decode(DefaultStudyData.self, from: Data(contentsOf: kojikotoURL))
        precondition(kojikoto.items.count == 2390)
        precondition(kojikoto.items.filter { $0.mastery == .starting }.count == 150)
        precondition(kojikoto.items.filter { $0.mastery == .learning }.count == 2104)
        precondition(kojikoto.items.filter { $0.mastery == .mastered }.count == 136)
        precondition(kojikoto.items[81].mastery == .starting)
        precondition(kojikoto.items[140].mastery == .mastered)
        precondition(kojikoto.items[141].mastery == .learning)
        precondition(kojikoto.items[360].mastery == .starting)
        precondition(kojikoto.items[0].answer == "匕首\n合口")
        precondition(kojikoto.items[140].notes == "逞筆さん141番")
        let withProverbs = LearningStore(fileURL: seededURL, defaults: defaults, additionalDefaults: [yoji, kojikoto])
        precondition(withProverbs.items.count == 6967)
        precondition(withProverbs.item(first.id) == personal)
        precondition(withProverbs.item(defaults.items[1].id) == nil)
        precondition(withProverbs.item(yoji.items[0].id) == nil)
        precondition(withProverbs.item(yoji.items[1059].id)?.mastery == .mastered)
        precondition(withProverbs.delete(kojikoto.items[0].id))
        precondition(withProverbs.setMastery(.mastered, for: kojikoto.items[141].id))
        let proverbRestart = LearningStore(fileURL: seededURL, defaults: defaults, additionalDefaults: [yoji, kojikoto])
        precondition(proverbRestart.items.count == 6966)
        precondition(proverbRestart.item(kojikoto.items[0].id) == nil)
        precondition(proverbRestart.item(kojikoto.items[141].id)?.mastery == .mastered)
        let onyomiURL = URL(fileURLWithPath: "KanjiBuildUp/Resources/OnyomiStudyData.json")
        let onyomi = try JSONDecoder().decode(DefaultStudyData.self, from: Data(contentsOf: onyomiURL))
        precondition(onyomi.items.count == 1030)
        precondition(onyomi.items.filter { $0.mastery == .starting }.count == 58)
        precondition(onyomi.items.filter { $0.mastery == .learning }.count == 13)
        precondition(onyomi.items.filter { $0.mastery == .mastered }.count == 959)
        precondition(onyomi.items[0].mastery == .mastered)
        precondition(onyomi.items[34].mastery == .starting)
        precondition(onyomi.items[194].mastery == .learning)
        precondition(onyomi.items[11].answer == "えんべん\nえんばん")
        precondition(onyomi.items.last?.notes == "逞筆さん1030番")
        precondition(onyomi.items.last?.question == "淤塞")
        let withOnyomi = LearningStore(fileURL: seededURL, defaults: defaults, additionalDefaults: [yoji, kojikoto, onyomi])
        precondition(withOnyomi.items.count == 7996)
        precondition(withOnyomi.item(first.id) == personal)
        precondition(withOnyomi.item(defaults.items[1].id) == nil)
        precondition(withOnyomi.item(yoji.items[0].id) == nil)
        precondition(withOnyomi.item(kojikoto.items[0].id) == nil)
        precondition(withOnyomi.item(kojikoto.items[141].id)?.mastery == .mastered)
        precondition(withOnyomi.delete(onyomi.items[0].id))
        precondition(withOnyomi.setMastery(.mastered, for: onyomi.items[194].id))
        let onyomiRestart = LearningStore(fileURL: seededURL, defaults: defaults, additionalDefaults: [yoji, kojikoto, onyomi])
        precondition(onyomiRestart.items.count == 7995)
        precondition(onyomiRestart.item(onyomi.items[0].id) == nil)
        precondition(onyomiRestart.item(onyomi.items[194].id)?.mastery == .mastered)
        let continuationURL = URL(fileURLWithPath: "KanjiBuildUp/Resources/OnyomiContinuationStudyData.json")
        let continuation = try JSONDecoder().decode(DefaultStudyData.self, from: Data(contentsOf: continuationURL))
        precondition(continuation.items.count == 3170)
        precondition(continuation.items.prefix(876).filter { $0.mastery == .mastered }.count == 750)
        precondition(continuation.items.prefix(876).filter { $0.mastery == .starting }.count == 60)
        precondition(continuation.items.prefix(876).filter { $0.mastery == .learning }.count == 66)
        precondition(continuation.items.dropFirst(876).allSatisfy { $0.mastery == .starting })
        precondition(continuation.items.first?.notes == "逞筆さん1031番")
        precondition(continuation.items[875].notes == "逞筆さん1906番")
        precondition(continuation.items[876].notes == "逞筆さん1907番")
        precondition(continuation.items[876].answer == "けんけん\nえんえん")
        precondition(continuation.items.last?.notes == "逞筆さん4200番")
        let allBatches = [yoji, kojikoto, onyomi, continuation]
        let completedOnyomi = LearningStore(fileURL: seededURL, defaults: defaults, additionalDefaults: allBatches)
        precondition(completedOnyomi.errorMessage == nil && completedOnyomi.items.count == 11164)
        // No. 1431 duplicates the question and answer of existing no. 804.
        precondition(completedOnyomi.item(continuation.items[400].id) == nil)
        precondition(completedOnyomi.item(onyomi.items[803].id) != nil)
        precondition(completedOnyomi.item(first.id) == personal)
        precondition(completedOnyomi.item(onyomi.items[0].id) == nil)
        precondition(completedOnyomi.item(onyomi.items[194].id)?.mastery == .mastered)
        precondition(completedOnyomi.delete(continuation.items[0].id))
        precondition(completedOnyomi.setMastery(.learning, for: continuation.items[876].id))
        let continuationRestart = LearningStore(fileURL: seededURL, defaults: defaults, additionalDefaults: allBatches)
        precondition(continuationRestart.items.count == 11163)
        precondition(continuationRestart.item(continuation.items[0].id) == nil)
        precondition(continuationRestart.item(continuation.items[876].id)?.mastery == .learning)
        let correctionURL = directory.appendingPathComponent("onyomi-correction.json")
        let previousItems = Dictionary(uniqueKeysWithValues: continuation.previousItems!.map { ($0.id, $0) })
        let oldBatch = DefaultStudyData(version: continuation.replacesVersion!, items: continuation.items.map { previousItems[$0.id] ?? $0 })
        let oldStore = LearningStore(fileURL: correctionURL, defaults: oldBatch)
        let changed = continuation.items.filter { previousItems[$0.id]?.mastery != nil && previousItems[$0.id]?.mastery != $0.mastery }
        precondition(oldStore.setMastery(.learning, for: changed[0].id))
        precondition(oldStore.delete(changed[1].id))
        var editedMeaning = oldStore.items.first { $0.notes == "逞筆さん1185番" }!
        editedMeaning.meaning = "自分で編集した意味"
        precondition(oldStore.update(editedMeaning))
        let correctedStore = LearningStore(fileURL: correctionURL, defaults: continuation)
        precondition(correctedStore.items.count == oldBatch.items.count - 1)
        precondition(correctedStore.item(changed[0].id)?.mastery == .learning)
        precondition(correctedStore.item(changed[1].id) == nil)
        precondition(correctedStore.item(changed[2].id)?.mastery == changed[2].mastery)
        precondition(correctedStore.item(editedMeaning.id)?.meaning == editedMeaning.meaning)
        precondition(correctedStore.setMastery(.mastered, for: changed[2].id))
        let correctionRestart = LearningStore(fileURL: correctionURL, defaults: continuation)
        precondition(correctionRestart.item(changed[2].id)?.mastery == .mastered)
        let untouchedURL = directory.appendingPathComponent("onyomi-meaning-correction.json")
        _ = LearningStore(fileURL: untouchedURL, defaults: oldBatch)
        let meaningCorrected = LearningStore(fileURL: untouchedURL, defaults: continuation)
        precondition(meaningCorrected.item(editedMeaning.id)?.meaning == continuation.items[154].meaning)
        let legacyURL = directory.appendingPathComponent("legacy.json")
        var existing = first
        existing.id = UUID(); existing.notes = "自分のメモ"; existing.mastery = .learning
        try JSONEncoder().encode([existing]).write(to: legacyURL)
        let upgraded = LearningStore(fileURL: legacyURL, defaults: defaults)
        precondition(upgraded.items.count == 2974 && upgraded.item(existing.id) == existing)
        precondition(upgraded.item(first.id) == nil)
        let corruptDefaults = LearningStore(fileURL: url, defaults: defaults)
        precondition(corruptDefaults.items.isEmpty && corruptDefaults.errorMessage != nil)
        let stillCorrupt = try String(contentsOf: url, encoding: .utf8)
        precondition(stillCorrupt == "corrupt")
        print("PASS: CSV formats/errors, Shift JIS, initial mastery, filtering, persistence, session, corrupted-file protection")
    }
}
